### ISSUE TITLE
[Feat] 주사기록화면에 코어데이터 붙이기

### ISSUE THREAD

**Issue by chaekie** [DeveloperAcademy-POSTECH/MC3-A-Team7#20]
# Description
 코어데이터 붙이고,
컬러에셋 적용하고,
네비게이션 적용하기

# Tasks
- [ ] 날짜, 부위에 대한 코어데이터 연결
- [ ] 메인화면에서 주사기록 화면으로 이동하기(탭뷰아닌 네비바 기존 디자인 적용)
- [ ] 컬러에셋 적용
- [ ] 올리의 코드리뷰 반영
<br>
