### ISSUE TITLE
[Feat]추천 제외 부위 화면 구현

### ISSUE THREAD

**Issue by chaekie** [DeveloperAcademy-POSTECH/MC3-A-Team7#31]
# Description
추천 제외 부위 화면을 구현합니다
픽커를 통해 추천 제외 부위를 추가하고
수정 기능을 통해 추천 가능 부위로 복구할 수 있습니다.

# Tasks
- [x] wheel picker로 전체 주사부위 숫자 보여주기(추천에서 제외된 부위는 제외)
- [x] 추가 버튼 누르면 추천에서 제외된 부위에 숫자 추가
- [x] 수정 버튼 누르면 숫자에 -버튼 활성화되고 추가버튼 비활성화
- [x] -버튼 누르면 숫자 사라짐
- [x] 저장 버튼 눌러야 최종 저장됨
- [x] 전체 스크롤 구현

**Comment by chaekie** [comment]
wheel picker로 전체 주사부위 숫자 보여주기(추천에서 제외된 부위는 제외) -> 추천에서 제외된 부위 남아있고 대신 중복된 것에 대해 alert 처리
