### ISSUE TITLE
[Feat] Dev2 - CoreData 관련 코드 작성하기

### ISSUE THREAD

**Issue by vanism2091** [DeveloperAcademy-POSTECH/MC3-A-Team7#39]
# Description
 코어데이터 관련 코드
1. Object에 관한 코드
2. 뷰관련

# Tasks
- [ ] Object에 관한 코드
    - [ ] enum InsulinType
    - [ ] enum TimeType
    - [ ] Injection Codegen -> Manual
- [ ] View에 관한 코드
    - [ ] 오늘의 추천 번호
    - [ ] 저장
    - [ ] 수정
    - [ ] 삭제
    - [ ] Fetch
        - [ ] NSPredicate+
        - [ ] NSSorting+

# ETC
작업하면서 Date+ 수정이 필요할 수도 있음
