### ISSUE TITLE
[Feat] 환경설정 화면 & 마지막 번호 변경 화면 추가

### ISSUE THREAD

**Issue by chaekie** [DeveloperAcademy-POSTECH/MC3-A-Team7#48]
# Description
환경설정 화면을 추가합니다.
환경설정 화면에서 “주사부위표 마지막 번호 변경”화면과 “추천 제외 부위 설정”화면을 연결합니다.
“주사부위표 마지막 번호 변경”화면은 온보딩 화면을 재사용합니다.

# Tasks
- [x] 환경설정 화면 기본 list 컴포넌트로 구현
- [x] 주사부위표 마지막 번호 변경 화면 온보딩 화면의 시작하기 버튼 라벨을 저장하기로 변경한 뒤 연결
- [x] 환경설정 화면에 “주사부위표 마지막 번호 변경”과 “추천 제외 부위 설정”화면 연결
<br>
