### ISSUE TITLE
[Feat] 히스토리 화면 개발

### ISSUE THREAD

**Issue by chaekie** [DeveloperAcademy-POSTECH/MC3-A-Team7#5]
# Description
주사기록 히스토리 화면 개발
날짜 버튼을 클릭하면 어떤 부위에 맞았는지 알 수 있게 주사부위표에 표시됨
맞은 부위 버튼(원 안에 있는 숫자)을 클릭하면 수정하기 액션과 이어짐

# Tasks
- [x] 날짜 버튼과 맞은 부위 버튼 가로 스크롤 컴포넌트 구현
- [x] 날짜 버튼과 맞은 부위 버튼 스크롤뷰
- [x] 날짜 버튼 클릭하면 맞은 부위에 컬러 변화
- [x] 맞은 부위 버튼을 클릭하면 수정하기 임시 액션 넣기
<br>

- [x] 주사부위표 컴포넌트 구현
- [x] 주사부위표는 스크롤시 고정
- [x] 날짜 버튼 클릭하면 주사부위표에 표시
<br>

- [x] 네비바 뒤로가기, 생성하기 버튼
