### ISSUE TITLE
[Feat] 생성_UpdateView

### ISSUE THREAD

**Issue by musclefrog** [DeveloperAcademy-POSTECH/MC3-A-Team7#6]
# Description
 - 생성/수정 뷰 구현

# Tasks
- [ ] 수정 모달창 만들기
- [ ] MainView에서 부위표 가져오기
- [ ] 부위 선택 시 숫자 버튼 색깔 변경
- [ ] 날짜 선택 시 DatePicker 띄우기
- [ ] 데이터 삭제 시 alert 띄우기
- [ ] 수정된 데이터 업데이트
