### ISSUE TITLE
[Feat] 생성_MainView

### ISSUE THREAD

**Issue by yeongminChae** [DeveloperAcademy-POSTECH/MC3-A-Team7#7]
# Description
 메인뷰 생성
 - 탭뷰를 이용하여, 배경 사각형 생성
 - 포인트 온탭시 스토로크 효과 생성
 - 기록하기 버튼 온탭시 다음번 권장 주사 부위 인덱스 업데이트

# Tasks
- [ ] 탭뷰 생성
- [ ] 포인트 온탭시 스트로크 이펙트 적용
- [ ] 권장 주사 부위 텍스트 표시
- [ ] 배꼽 표시
- [ ] DB연결
- [ ] CRUD중 ( C,R ) 데이터 처리
- [ ] 수정 뷰로 이동위한 코드 처리
- [ ] 기록하기 클릭 시 다음 번 권장 주사 부위 추천
 

 # ETC
...
